name: ProgramCodeConvention
on:
  push:
      branches: main

jobs:
  ProgramCodeConvention:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code in Repo
        uses: actions/checkout@v3
      - name: Lint ProgramCodeConvention
        uses: github/super-linter@v4
        env:
          VALIDATE_SQL: true
          FILTER_REGEX_INCLUDE: ./*.sql
          GITHUB_TOKEN: ${{secrets.TOKEN}}
