name: Test Cases
on:
  push:
    branches: main

jobs:
  TestCases:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: "actions/checkout@v3"
      
      - name: Compile
        run: |
          echo Compile
          echo TestCasesModified.yml-test
          cd $GITHUB_WORKSPACE/.github/workflows/
          pwd
          echo $GITHUB_WORKSPACE
          ls -all TestCasesModified.java
          echo $JAVA_HOME
          export CLASSPATH="./ojdbc8.jar:./"
          javac TestCaseModified.java
      
      - name: Execute
        run: |
          echo Execute
          cd $GITHUB_WORKSPACE/
          pwd
          echo $GITHUB_WORKSPACE
          ls -all TestCasesModified.java
          echo $JAVA_HOME
          export CLASSPATH="./ojdbc8.jar:./"
          echo "$env:LOGIN"
          java TestCaseseModified ${{secrets.LOGIN}} ${{secrets.PASSWORD}}
